repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run Ruff
        entry: ruff
        language: python
        language_version: python3.10
        types: [python]
        args: ["."]
        additional_dependencies:
          - ruff==0.12.0