services:
  retrieval-system:
    build:
      context: ./src/retriever
      args:
        APP_PORT: 8000
    container_name: retrieval-system-backend
    env_file:
      - ./src/retriever/.env
    ports:
      - "8000:8000"
  
  rerank-system:
    build:
      context: ./src/reranker
      args:
        APP_PORT: 8080
    container_name: rerank-system-backend
    env_file:
      - ./src/reranker/.env
    ports:
      - "8080:8080"